# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Blog da Anna
email: anna.luiza.araujo@hotmail.com
description: >
  Um blog de uma eterna aprendiz que ama passar os seus conhecimentos.
baseurl: "/blog"
url: "https://alpaula.github.io/"
twitter_username: alpaula_
github_username:  alpaula

# Build settings
markdown: kramdown
permalink: /:title/
